const actionType = {
    SET_ITEM_TYPE: "SET_ITEM_TYPE",
    ADD_ITEM_SUPPLIER_LIST:"ADD_ITEM_SUPPLIER_LIST",
    HID_MODAL_SUPPLIER:"HID_MODAL_SUPPLIER",
    TOGGLE_ICON:"TOGGLE_ICON",
    ADDED_IMAGE_SUPPLIER_MODAL:"ADDED_IMAGE_SUPPLIER_MODAL"

  };
  
  export default actionType;
   