const actionType = {
  ADD_ITEM_FASETING_LIST: "ADD_ITEM_FASETING_LIST",
  ADD_ITEM_COLOR_LIST: "ADD_ITEM_COLOR_LIST",
  TOGGLE_MODAL:"TOGGLE_MODAL",
  TOGGLE_MODAL_FASET:"TOGGLE_MODAL_FASET",
  CLEAR_PRICE_MODAL_LIST:"CLEAR_PRICE_MODAL_LIST",
  TAKE_COLOR_DATA:"TAKE_COLOR_DATA",
  TAKE_FASETING_DATA:"TAKE_FASETING_DATA",
  HANDLE_RATE_VALUE:"HANDLE_RATE_VALUE",
  ADD_PRIC_LIST:"ADD_PRIC_LIST",
  SELECTED_ITEM_ID:"SELECTED_ITEM_ID",
  UPDATE_PRICE_LIST:"UPDATE_PRICE_LIST"
};

export default actionType;
